### ISSUE TITLE
Exercism: Phone Number - Peter Wooden

### ISSUE THREAD

**Issue by peterwooden** [sydneyelixir/sydneyelixir.github.io#6]
Short talk covering the Exercism for September and how I implemented my solution.

**Comment by paulfioravanti** [comment]
Awesome, thanks, @peterwooden! You're in the line up for next month!

**Comment by paulfioravanti** [comment]
Hey @peterwooden, just wanted to confirm a couple of things:

- Is this your Twitter account? https://twitter.com/peterwooden If not, and I'm misremembering, do you have one? If so, what is it?
- If the Twitter account is correct, is using the photo there okay in the Elixir Sydney slide deck? If not, or that's not your Twitter account, can you please provide a photo?

**Comment by peterwooden** [comment]
Hi Paul,

Yes, thats my twitter, happy for you to use the photo in it!
