### ISSUE TITLE
Exercism: Hamming Distance - Will Tan

### ISSUE THREAD

**Issue by twillzy** [sydneyelixir/sydneyelixir.github.io#7]
"Short talk covering the Exercism for October and how I implemented my solution." - @peterwooden

Twitter: https://twitter.com/twillzy89
@paulfioravanti You have my consent using my twitter photo for Elixir Sydney slide deck.

**Comment by paulfioravanti** [comment]
Thanks for the awesome talk, @twillzy ! If you wanted to share your slideware, feel free to export them to PDF, and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and tweet the slides link out to `@ElixirSydney`, and we'll give it a retweet
