### ISSUE TITLE
Elixir for Functional Programmers (and everyone else)

### ISSUE THREAD

**Issue by rellen** [sydneyelixir/sydneyelixir.github.io#81]
**MAY** meetup
Will join ONLINE via Zoom
30mins
[@robertellen](https://twitter.com/robertellen) on twitter

### Brief summary of the talk content

Elixir as a language has stabilised very quickly in its 1.x days, and it's hard to imagine what Elixir 2.0 might even require.  One thing that is often cited as missing, however, is a static type system.  The core team has listened, and now work on a type system for Elixir is underway.  In the mean time, there are tools we can use home-grown in the Erlang ecosystem, or from the rest of the functional programming world, to help write less wrong Elixir.
In this talk, we will review what makes Elixir a functional programming language in the first place, before delving into some of the tools available.  We'll cover Success Typing with Dialyzer, Gradual Typing with Gradient, Property-Based Testing, and typeclasses and ADTs from Witchcraft/Algae.  We will also have a look at the sneak-peak of the new type system for Elixir that is currently being developed.

### Tentative Agenda

- dialyzer - 5m
- gradualizer / gradient - 15m
- property testing (stream data and proper) - 10m
- typeclasses and ADTs etc (e.g. Witchcraft/Algae etc) - 10m
- Elixir type system - 10m

**Comment by joshprice** [comment]
Thanks @rellen ! Looking forward to this one.
