### ISSUE TITLE
Hot-Code Upgrades with Castle

### ISSUE THREAD

**Issue by ausimian** [sydneyelixir/sydneyelixir.github.io#83]
Thanks for proposing a talk for Elixir Sydney!

Please provide the following information:

- Brief summary of the talk content

Hot-code upgrades, how they work and why the Castle library helps.

- Which month's meetup you would like to present at

December 6th 2023

- Will the talk be given in-person or online

In-person
- Length of talk (Max 30 minutes, but feel free to take less time; the more succinct, the better!)

20-30 mins

**Comment by mbuhot** [comment]
Thanks @ausimian, I've added your talk to the December meetup https://www.meetup.com/elixir-sydney/events/297411848/

**Comment by mbuhot** [comment]
The presentation has been published to the ElixirAustralia YouTube channel: https://www.youtube.com/watch?v=OwsEDm_18Os

Thanks again @ausimian
