### ISSUE TITLE
Easy Parser Combinator with PEG

### ISSUE THREAD

**Issue by TwistingTwists** [sydneyelixir/sydneyelixir.github.io#84]
Thanks for proposing a talk for Elixir Sydney!

#### Brief summary of the talk content

* How to write parser combinators using PEG grammars? 
* Combining NimbleParsec and Pegasus - livebook demo.

####  Which month's meetup you would like to present at

* March 2024 / April 2024 / May 2024

####  Will the talk be given in-person or online

online

####  Length of talk (Max 30 minutes, but feel free to take less time; the more succinct, the better!)

20 - 30 minutes 

####  Where you can be found on the internet (e.g. personal website, social media account links etc)

Telegram - [t.me/linkedin132](https://t.me/linkedin132)
Twitter - [twitter.com/twistin456](https://twitter.com/twistin456)

**Comment by mbuhot** [comment]
Hi @TwistingTwists - would you be able to present this talk on Wed March 20?

**Comment by TwistingTwists** [comment]
@mbuhot 
Yes. Will update demo livebooks very soon!

**Comment by mbuhot** [comment]
Hi @TwistingTwists 👋 

Could you please confirm you're all good to present this Wednesday by joining the meetup event: https://www.meetup.com/elixir-sydney/events/299434628/

Thanks!

**Comment by TwistingTwists** [comment]
https://github.com/TwistingTwists/learning-concurrent-elixir/blob/b65921ee11b09ff1a6b78175ea3f485cc6b23b02/peg_parsers.livemd

Find the relevant file here :)

**Comment by mbuhot** [comment]
Thanks for the presentation @TwistingTwists 👍
