### ISSUE TITLE
Fast and efficient image processing in Elixir

### ISSUE THREAD

**Issue by kipcole9** [sydneyelixir/sydneyelixir.github.io#85]
Images influence every aspect of an application design and UX. They comprise a significant amount of the payload for many apps. This talk looks at how the combination of [libvips](libvips.org), [vix](https://github.com/akash-akya/vix) and [image](https://github.com/kipcole9/image) can be used to:

* Scale, resize, transform and compose images fast and efficiently
* Streaming image pipelines from the front end through to external storage services
* [Announcement at Elixir meetup] Deliver the right image size dynamically to Plug-based apps
* [Experimental] Vectorise raster images to SVG for fun - and for efficient image placeholders

- Which month's meetup you would like to present at
March, May or June

- Will the talk be given in-person or online 
In person

- Length of talk (Max 30 minutes, but feel free to take less time; the more succinct, the better!)
30m

- Where you can be found on the internet (e.g. personal website, social media account links etc)
https://github.com/kipcole9

- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find 
https://github.com/kipcole9

**Comment by TwistingTwists** [comment]
This sounds exciting! 
Very looking forward to this one!

**Comment by mbuhot** [comment]
Thanks for presenting @kipcole9 !
The recording of the talk is available at https://www.youtube.com/watch?v=H-Psxgqoa-M
