### ISSUE TITLE
What's in a name? Addressing people by the right name at the right time around the world

### ISSUE THREAD

**Issue by kipcole9** [sydneyelixir/sydneyelixir.github.io#86]
Audience engagement is a critical factor in application success. And engaging with people requires addressing them the right way.  How you are addressed will depend on whether I'm representing the tax department, a close friend, family, a social media site or a civil or military honours organisation.  Thats hard enough in English. But names are even more interesting and diverse in other cultures.

This talk looks at recent work by the [CLDR](https://cldr.unicode.org) [Person Names](https://cldr.unicode.org/translation/miscellaneous-person-name-formats) working group to formalise name formatting and introduces `ex_cldr_person_names` as the latest addition to the [ex_cldr](https://github.com/elixir-cldr) family of localisation libraries.

- Which month's meetup you would like to present at
March, May or June, August

- Will the talk be given in-person or online
In person

- Length of talk (Max 30 minutes, but feel free to take less time; the more succinct, the better!)
30m

- Where you can be found on the internet (e.g. personal website, social media account links etc)
https://github.com/kipcole9

- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck
https://github.com/kipcole9

**Comment by suranyami** [comment]
Great idea for a talk!

**Comment by mbuhot** [comment]
Hi @kipcole9 - would you be able to present this talk on Wed March 20?

**Comment by kipcole9** [comment]
Mike, yes, can do. Just the push I need to get it finished up 😀Sent from my iPhoneOn 26 Feb 2024, at 18:21, Mike Buhot ***@***.***> wrote:﻿
Hi @kipcole9 - would you be able to present this talk on Wed March 20?

**Comment by mbuhot** [comment]
Video for the talk is now on YouTube: https://youtu.be/pBR-n_dA3lo?si=ZBwaLoVWRXelrLKT
