### ISSUE TITLE
BulmaComponents: a new CoreComponents library for Phoenix

### ISSUE THREAD

**Issue by suranyami** [sydneyelixir/sydneyelixir.github.io#87]
## Summary
Although Tailwind CSS is everywhere in the Phoenix ecosystem, I thought it was time to add an alternative that uses `bulma` (https://bulma.io). We'll look through how it's structured, and what it looks like in both HTML markup and using `PhoenixStorybook`.

Meetup: March 2024, in-person
Time: approx 15 mins

https://suranyami.com
https://github.com/suranyami
@suranyami on Mastadon, etcetera

![Day-V Ragnar](https://github.com/elixirsydney/elixirsydney/assets/69984/59a6b66b-d2a2-4a57-b84e-5bfc4141a19d)

**Comment by mbuhot** [comment]
Hi @suranyami - are you available to present this talk at the June 26th meetup? 
https://www.meetup.com/elixir-sydney/events/300298664/
