### ISSUE TITLE
Tools for runtime validation of types

### ISSUE THREAD

**Issue by Nickphammond** [sydneyelixir/sydneyelixir.github.io#88]
**- Name of talk (in the title field):** 
Tools for runtime validation of types

**- Brief summary of the talk content:**
Talk about my experiences with playing around with a few tools that do runtime validation of types

**- Which month's meetup you would like to present at**
April/May

**- Will the talk be given in-person or online**
Ideally in person

**- Length of talk (Max 30 minutes, but feel free to take less time; the more succinct, the better!)**
I wouldn't say much over 20 minutes

**Comment by mbuhot** [comment]
Hi @Nickphammond, thanks for creating this issue. 
I've tentatively added this to the April meetup, which should be around the 17th. 
Not sure if we're going to be online-only or in-person since ElixirConf EU is on the 18th - we'll keep you updated :)

**Comment by mbuhot** [comment]
Thanks for presenting @Nickphammond 👍 
The recording of the talk is at: https://www.youtube.com/watch?v=Du9Xw8Rf0Io
