### ISSUE TITLE
The new Set-Theoretic Type System for Elixir

### ISSUE THREAD

**Issue by rellen** [sydneyelixir/sydneyelixir.github.io#89]
- Brief summary of the talk content
  TBD - depends on where the implementation is at by the time of the talk
- Which month's meetup you would like to present at
  July or later - I'll be giving a similar talk at BFPG around this time and I have talks in the mean time I need to concentrate on first
- Will the talk be given in-person or online
   Online
- Length of talk (Max 30 minutes, but feel free to take less time; the more succinct, the better!)
  30 mins

**Comment by mbuhot** [comment]
Let's see if there's any news coming out of Elixir Conf EU next month. Hopefully some progress has been made towards propagating type info through patterns, guards and struct field types.

**Comment by mbuhot** [comment]
@rellen would you like to give a "Hands-on with the Elixir 1.17 type system" at the July meetup?

**Comment by rellen** [comment]
Yes, I would be happy to, @mbuhot
