### ISSUE TITLE
Build, deploy, and expose a LiveView microservice the easy way with Traefik

### ISSUE THREAD

**Issue by andypalmer** [sydneyelixir/sydneyelixir.github.io#91]
- Brief summary of the talk content
Live demonstration of making a simple Phoenix LiveView app, building a docker image and deploying to a docker host running traefik as reverse proxy (including automatic letsencrypt certificate fetching). If all goes according to plan 🙏 , we'll have the app built and publically available at the end of the session (including content from audience interaction).
- Which month's meetup you would like to present at
June
- Will the talk be given in-person or online
In-person
- Length of talk (Max 30 minutes, but feel free to take less time; the more succinct, the better!)
~30 minutes
- Where you can be found on the internet (e.g. personal website, social media account links etc)
Twitter - [@andypalmer](https://twitter.com/andypalmer)

**Comment by mbuhot** [comment]
Hi @andypalmer, are you available to give this talk this week on Wednesday 24th July?

**Comment by andypalmer** [comment]
Hi @mbuhot, I wouldn't be available to do this for July or August.
