### ISSUE TITLE
A Practical Guide to Machine Learning in Elixir

### ISSUE THREAD

**Issue by cigrainger** [sydneyelixir/sydneyelixir.github.io#92]
Thanks for proposing a talk for Elixir Sydney!

Please provide the following information:

> Name of talk (in the title field)

A Practical Guide to Machine Learning in Elixir

> Brief summary of the talk content

At Amplified, we've been putting ML in production with Elixir since the very early days of Nx in 2022. This talk is a practical guide to doing the same, informed by our experiences and the lessons we've learned. Because every project, company, and machine learning task is different, I will combine a general 'roadmap' approach with insights shaped by our particular set of problems and perspectives. We managed to go all in on Elixir, ridding our stack of Python entirely, and I believe (in most cases) you can too.

> Which month's meetup you would like to present at

June or July

> Will the talk be given in-person or online

Online, sadly

> Length of talk (Max 30 minutes, but feel free to take less time; the more succinct, the better!)

I'd like to say 20-25, but I'm verbose on a good day so let's say 30.

> Where you can be found on the internet (e.g. personal website, social media account links etc)

https://cigrainger.com
https://twitter.com/cigrainger
https://github.com/cigrainger

> Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)

![Image](https://github.com/elixirsydney/elixirsydney/assets/3984794/30309396-5689-49c6-a412-b874f291abe5)

**Comment by mbuhot** [comment]
Thanks for the great presentation @cigrainger 🙏 
The talk is now available on YouTube: https://www.youtube.com/watch?v=Es08MRtSkoE
