### ISSUE TITLE
Working with OpenAI APIs in Elixir

### ISSUE THREAD

**Issue by joshprice** [sydneyelixir/sydneyelixir.github.io#93]
Discover the power of integrating OpenAI's cutting-edge APIs into your Elixir applications. This talk will guide you through the essentials of setting up, authenticating, and making requests to OpenAI's API using Elixir. We'll cover practical examples, best practices, and common pitfalls, ensuring you leave equipped to harness the full potential of AI in your projects. Whether you're building chatbots, generating content, or exploring new AI-driven functionalities, this session will provide the knowledge and tools you need to succeed.

June 2024, In person, 20-30 mins

**Comment by mbuhot** [comment]
Thanks Josh, the video is now up on YouTube: https://www.youtube.com/watch?v=9d1y1x8Ezpw
